---
- name: ack | Install ack.
  get_url:
    url=http://beyondgrep.com/ack-2.12-single-file
    dest=/usr/local/bin/ack
  ignore_errors: yes

- file:
    path=/usr/local/bin/ack
    mode=0755
  ignore_errors: yes
